name: texpense
description: "Ứng dụng quản lý chi tiêu cá nhân"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# ====================================================================================================

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For networking
  dio: ^5.3.3 # A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
  retrofit: ^4.0.3 # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.

  # For architecture
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  #  flutter_modular: ^6.3.2 # Smart project structure with dependency injection and route management
  #  flutter_bloc: ^8.1.3 # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  #  hydrated_bloc: 9.1.2 #An extension to package:bloc which automatically persists and restores bloc and cubit states. Built to work with package:bloc.

  # For model
  equatable: ^2.0.5 # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  json_annotation: ^4.8.1 # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  freezed_annotation: ^2.4.1 # Annotations for the freezed code-generator. This package does nothing without freezed too.

  # For Firebase
  firebase_core: 2.27.0 # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  cloud_firestore: 4.15.8
  firebase_auth: 4.17.8
  google_sign_in: ^6.2.1
  #  firebase_messaging:
  #    path: ./packages/firebase_messaging # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  #  firebase_storage: 11.6.9 # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  #  firebase_remote_config: 4.3.17 # Flutter plugin for Firebase Remote Config. Update your application look and feel and behavior without re-releasing.
  #  firebase_crashlytics: 3.4.18 # Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the Firebase console.
  #  firebase_analytics: 10.8.9 # Flutter plugin for Google Analytics for Firebase, an app measurement solution that provides insight on app usage and user engagement on Android and iOS.
  #  firebase_dynamic_links: 5.4.17 # Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating and handling links across multiple platforms.

  # For local storage
  path_provider: ^2.1.1 # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  #  hive: ^2.2.3 # Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  #  flutter_secure_storage: ^9.0.0 # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  shared_preferences: ^2.2.3

  # For local notification
  #  flutter_local_notifications: ^16.1.0 # A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.

  # For Ads
  #  flutter_insider: ^3.9.3+nh # Flutter Plugin For Insider SDK
  #  appsflyer_sdk: ^6.14.3 # Flutter Plugin For AppsFlyer SDK

  # For multiple languages
  intl: ^0.18.1 # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  #  multiple_localization: 0.4.0 # Support for multiple abr and messages localization files for intl package.

  # For Crypto
  cryptography: ^2.7.0 #Popular cryptographic algorithms for Dart / Flutter developers.
  encrypt: ^5.0.3 #generate cryptographically secure random keys and IVs for you project.
  #  dart_des: ^1.0.2 #riple DES is either DES-EDE3 with a 24 byte key, or DES-EDE2 with a 16 byte key.
  #  charset: ^2.0.1 #cp series,win series,iso series,gbk,euc-kr,euc-jp,shift-jis,cp437,utf-16 and utf-32 Encoding and Decoding
  #  bcrypt: ^1.1.3 #This package use jBCrypt modified code to work with Dart VM.

  # For utils
  logger: ^2.0.2+1 # Small, easy to use and extensible logger which prints beautiful logs.
  permission_handler: ^10.4.5 # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.Ø
  #  package_info_plus: ^4.2.0 # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android.
  enum_to_string: 2.0.1 # Better conversion of ENUMs to string. Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
  formz: ^0.6.1 # A unified form representation in Dart which aims to simplify form representation and validation in a generic way.
  #  local_auth: ^2.1.7 # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  crypto: 3.0.3 # Implementations of SHA, MD5, and HMAC cryptographic functions
  #  share_plus: ^7.2.1 # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  #  currency_text_input_formatter: 2.1.10 # Currency Text Input Formatter for Flutter. Use it easy and simple for your flutter app.
  #  screenshot: ^2.1.0 # Capture widgets as Images not rendered on the screen
  #  image_gallery_saver: 2.0.3 # Save screenshot images to the gallery
  collection: ^1.17.2 # Collections and utilities functions and classes related to collections.
  #  flutter_image_compress: ^2.1.0 # Compress image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
  connectivity_plus: ^6.0.3 # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  #  fluttercontactpicker: 4.7.0 # Interact with native OS contact pickers using Flutter
  cached_network_image: ^3.3.0 # Show images from the internet and keep them in the cache directory
  #  crclib: 3.0.0 # Collection of cyclic redundancy check (CRC) routines as Dart converters.
  #  uni_links: ^0.5.1 # help with App/Deep Links (Android) and Universal Links and Custom URL schemes (iOS).
  #  url_launcher: ^6.2.1 #A Flutter plugin for launching a URL.
  #  android_intent_plus: ^4.0.3 #This plugin allows Flutter apps to launch arbitrary intents when the platform is Android.
  #  archive: ^3.4.6 # Provides encoders and decoders for various archive and compression formats such as zip, tar, bzip2, gzip, and zlib.
  #  app_tracking_transparency: 2.0.4 # This Flutter plugin allows you to display ios tracking authorization dialogue and request permission to collect data.
  #  app_version_update: 4.0.1 # An easy and quick way to check if the local app is updated with the same version in their respective stores (Play Store / Apple Store ).
  #  flutter_keyboard_visibility: 5.4.1 # Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
  #  camera: ^0.10.5+5 # A Flutter plugin for iOS, Android and Web allowing access to the device cameras.
  #  file_picker: ^6.0.0 # A package that allows you to use the native file explorer to pick single or multiple files, with extensions filtering support.
  #  flutter_tts: ^3.8.3 # A flutter plugin for Text to Speech. This plugin is supported on iOS, Android, Web, & macOS.
  #  flutter_cached_pdfview: ^0.4.2 # A package to show Native PDF View for iOS and Android, support Open from a different resource like Path, Asset or Url and Cache it.
  #  open_file_plus: ^3.4.1 # A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
  auto_route: ^7.9.2
  get_it: ^7.6.7

  # For UIs
  flutter_svg: ^2.0.8 # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  lottie: ^3.1.2 # Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
  gap: 3.0.1 # Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  #  just_the_tooltip: 0.0.12 # A multi directional tooltip used to display any content with inbuilt support for list views
  modal_bottom_sheet: ^3.0.0-pre # Create awesome and powerful modal bottom sheets. Material, Cupertino iOS 13 or create your own style
  #  webview_flutter: ^4.4.2 # A Flutter plugin that provides a WebView widget on Android and iOS.
  #  image_picker: ^1.0.4 # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  #  auto_size_text: ^3.0.0 # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  #  smart_auth: 1.1.1 # Wrapper of Android SMS User Consent API, SMS Retriever API to read one time sms code, get/save/delete user phone number, OTP, OTC, sms autofill, android autofill
  #  fdottedline_nullsafety: 2.0.1 # Use the easiest way to create a dotted line view
  #  carousel_slider: 4.2.1 # A carousel slider widget, support infinite scroll and custom child widget.
  #  dots_indicator: ^3.0.0 # Dots indicator to show progression of a PageView for example
  overlay_support: 2.1.0 # Provider support for overlay, easy to build toast and internal notification
  #  table_calendar: 3.0.9 # Highly customizable, feature-packed calendar widget for Flutter.
  #  animated_toggle_switch: 0.5.2 # Simple and animated toggle switch for multiple choices. It's a good alternative if you don't want to use something like a dropdown menu.
  dotted_border: ^2.1.0 # A flutter package to easily added dotted borders around widgets.
  #  qr_flutter: ^4.1.0 # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  #  flutter_staggered_grid_view: 0.7.0 # Provides a collection of Flutter grids layouts.
  #  syncfusion_flutter_charts: ^23.1.42 # A Flutter Charts library which includes data visualization widgets such as cartesian and circular charts, to create real-time, interactive, high-performance, animated charts.
  #  sliding_up_panel: ^2.0.0+1 # A draggable Flutter widget that makes implementing a SlidingUpPanel much easier!
  #  expandable: 5.0.1 # A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
  #  flutter_html: ^3.0.0-alpha.6 # A Flutter widget rendering static HTML and CSS as Flutter widgets.
  #  animated_text_kit: ^4.2.2 # A flutter package which contains a collection of some cool and awesome text animations.
  #  flutter_animate: 4.2.0+1 # A performant library that makes it simple to add almost any kind of animated effect in Flutter.
  #  countup: 0.1.4 # A Flutter package to create easy slide animation countdown / countup timer.
  #  badges: ^3.1.2 # A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  #  barcode: ^2.0.4 # Barcode generation library for Dart that can generate generic drawing operations for any backend.
  #  flutter_app_badger: ^1.5.0 # Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
  #  dart_ipify: ^1.1.1 # This package uses the remote ipify web services in order to get your public IP address or geographical details from any given IP.
  #  flutter_contacts: ^1.1.7+1 # Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with group support, vCard support, and contact permission handling.
  #  confetti: ^0.7.0 # Blast some confetti all over the screen and celebrate user achievements!
  #  styled_text: ^8.1.0 # Text widget with formatted text using tags. Makes it easier to use formatted text in multilingual applications.
  emoji_picker_flutter: ^2.1.1 # A Flutter package that provides an Emoji picker widget with 1500+ emojis in 8 categories.
  #  app_settings: ^5.1.1 # A Flutter plugin for opening iOS and Android phone settings from an app.
  google_fonts: 6.1.0
  flutter_native_splash: ^2.3.10
  animated_text_kit: ^4.2.2

  #for location
  #  geolocator: 9.0.2 # A Flutter geolocation plugin which provides easy access to platform specific location services
  #  geocoding: ^2.1.1 # A Flutter Geocoding plugin which provides easy geocoding and reverse-geocoding features.

  # for video call & chat
  http: ^1.2.0 #The http package provides the simplest way to fetch data from the internet.
  flutter_linkify: ^6.0.0 #Turns text URLs and emails into clickable inline links in text for Flutter.
  riverpod_generator: ^2.4.0

  # -------------------- LOCAL PACKAGES --------------------
  #  sizer: # Flutter Sizer helps implement a reponsive layout by providing helper widgets and extensions.
  #    path: ./packages/flutter_sizer
  #  device_info_plus: # Flutter plugin providing detailed information about the device (make, model, etc.), and Android or iOS version the app is running on.
  #    path: ./packages/device_info_plus
  #  biometric_helper: # Help to check Biometric change or not
  #    path: ./packages/biometric_helper
  flutter_code_gen:
    path: ./packages/flutter_code_gen

dev_dependencies:
  # For generate files
  build_runner: ^2.4.9 # A build system for Dart code generation and modular compilation.
  analyzer: ^6.2.0 #This package provides a library that performs static analysis of Dart code. It is useful for tool integration and embedding.
  freezed: ^2.4.5 # Code generation for immutable classes that has a simple syntax/API without compromising on the features.

  # For generate assets
  flutter_gen_runner: ^5.3.2 # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.

  # For generate networking
  retrofit_generator: ^8.0.2 # Retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  json_serializable: ^6.3.1 # Automatically generate code for converting to and from JSON by annotating Dart classes.

  flutter_lints: ^4.0.0
  custom_lint:
  riverpod_lint: ^2.3.1

  auto_route_generator: ^7.3.2

  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors
  assets:
    outputs:
      class_name: AppAssets
      package_name: texpense
      # Assets.imagesChip

      style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      # style: dot-delimiter

      package_parameter_enabled: false
      directory_path_enabled: true
      parse_metadata: true
      excludes:
#        - folder-your-want-to-exclude/*
#        - specified-asset.jpg

flutter:
  uses-material-design: true
  assets:
    # Level 1
    - assets/
    # Level 2
    - assets/icons/
    - assets/fonts/
    - assets/colors/
    - assets/images/
    - assets/svg/

  fonts:
    - family: TExpense-Font-Icon
      fonts:
        - asset: assets/fonts/texpense_font_icon.ttf

#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
