name: flutter_code_gen
description: "The Flutter code generator for your IcoMoon json file, Code Base (Clean Architecture with Bloc, Bloc Cubit, ...)"
version: 1.0.0-beta.4
homepage: https://github.com/toilathor/texpense/tree/master/packages/flutter_code_gen
repository: https://github.com/toilathor/texpense/tree/master/packages/flutter_code_gen
documentation: https://github.com/toilathor/texpense/tree/master/packages/flutter_code_gen
issue_tracker: https://github.com/toilathor/texpense/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  recase: ^4.1.0
  build: ^2.4.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  args: ^2.5.0
  yaml: ^3.1.2
  glob: ^2.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^6.5.4
  source_gen: any

platforms:
  android:
  ios:
  linux:
  macos:
  windows: